In [ ]:
import pandas as pd
import numpy as np

constructors = pd.read_csv('_final_project/1-Formula_One/constructors.csv')
results = pd.read_csv('_final_project/1-Formula_One/results.csv')
races = pd.read_csv('_final_project/1-Formula_One/races.csv')

constructor_group = results.groupby(by = "constructorId")
constructor_mean_points = constructor_group["points"].mean()
display(constructor_mean_points)

mean_points_sorted = constructor_mean_points.sort_values(ascending = False)
display(mean_points_sorted.iloc[:5])

constructors_subset = constructors[["constructorId", "name"]]

top5_constructors = pd.merge(mean_points_sorted, constructors_subset, on = "constructorId", how = "left")
display(top5_constructors.head(5),)
#top 5 cars with best performance overall

In [7]:
races_subset = races[["raceId", "year"]]
results_subset = results[["raceId", "constructorId","position"]]

results_year = pd.merge(results_subset, races_subset, on="raceId", how="left")
display(results_year)
#add code here to filter out the cars we are not analyzing.

plotting_data = results_year.query('constructorId == [131, 9, 23, 208, 6]')

display(plotting_data)

       raceId  constructorId position  year
0          18              1        1  2008
1          18              2        2  2008
2          18              3        3  2008
3          18              4        4  2008
4          18              1        5  2008
...       ...            ...      ...   ...
25655    1086            210       16  2022
25656    1086              3       17  2022
25657    1086              3       18  2022
25658    1086            213       19  2022
25659    1086             51       20  2022

[25660 rows x 4 columns]

       raceId  constructorId position  year
7          18              6        8  2008
12         18              6       \N  2008
13         18              9       \N  2008
16         18              9       \N  2008
22         19              6        1  2008
...       ...            ...      ...   ...
25641    1086            131        2  2022
25642    1086            131        3  2022
25643    1086              6        4  2022
25644    1086              9        5  2022
25645    1086              6        6  2022

[3737 rows x 4 columns]

In [ ]:
# Rank top 5 drivers by mean points
drivers_subset = drivers[["driverId", "forename", "surname"]]

driver_mean_points = results.groupby(by="driverId")["points"].mean()
driver_mean_points_sorted = driver_mean_points.sort_values(ascending=False)

top5_drivers = pd.merge(driver_mean_points_sorted, drivers_subset, on="driverId", how="left")
display(top5_drivers.head(5))

# Find most frequent constructor for each top 5 driver
top5_driver_ids = top5_drivers["driverId"].iloc[:5].tolist()
top_driver_results = results[results["driverId"].isin(top5_driver_ids)]

constructor_counts = top_driver_results.groupby(["driverId", "constructorId"]).size()
most_frequent = constructor_counts.groupby(level="driverId").idxmax()
most_frequent = pd.DataFrame(most_frequent.tolist(), columns=["driverId", "constructorId"])

final = pd.merge(most_frequent, drivers_subset, on="driverId", how="left")
final = pd.merge(final, constructors_subset, on="constructorId", how="left")
display(final[["forename", "surname", "name"]])

NameError: name 'races' is not defined